source 'https://github.com/CocoaPods/Specs.git'

target 'MRTableBuilder', :exclusive => true do
  pod "MRTableBuilder", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MRTableBuilder", :path => "../"

  
end
